# ==================
# Site Configuration
# ==================
title: Runnable Documentation
email: support@runnable.com
description: Articles to help those who use Runnable.com
url: https://docs.runnable.com
baseurl:
twitter:
  usertitle: GetRunnable
facebook:
  publisher: Runnable
seo:
  type: TechArticle

# ====================
# Server Configuration
# ====================
livereload: true
host: 0.0.0.0

# ===================
# Build Configuration
# ===================
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:categories/:title
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: page
  -
    scope:
      path: ""
      type: "posts"
    values:
      seo:
        type: TechArticle 

sass:
  sass_dir: _sass/

# ==================
# External Variables
# ==================
sidebar:
  - 
    title: Configuring a Repository
    category: repositories
  - 
    title: Configuring Other Services
    category: services
  - 
    title: Using Docker Compose
    category: docker-compose
  - 
    title: Networking
    category: networking
  - 
    title: Automated Testing
    category: testing
  - 
    title: Enterprise
    category: enterprise
  - 
    title: Integrations
    category: integrations
  - 
    title: Runnable CLI
    category: cli
  - 
    title: Privacy & Security
    category: privacy
  - 
    title: Pricing
    category: pricing
  - 
    title: Troubleshooting
    category: troubleshooting
